import styled from 'styled-components';

export const Section = styled.section`padding: 140px 32px; color: ${({ theme }) => theme.colors.dark}; background: ${({ theme }) => theme.colors.light}; scroll-margin-top: 90px; @media (max-width: ${({ theme }) => theme.breakpoints.sm}) { padding: 92px 16px; }`;
export const Inner = styled.div`width: min(100%, ${({ theme }) => theme.layout.contentMax}); margin: 0 auto;`;
export const Header = styled.div`display: grid; grid-template-columns: 1.2fr .7fr; align-items: end; gap: 60px; margin-bottom: 56px; @media (max-width: ${({ theme }) => theme.breakpoints.md}) { grid-template-columns: 1fr; gap: 22px; }`;
export const Kicker = styled.a`width: fit-content; margin-bottom: 18px; display: flex; align-items: center; gap: 9px; color: ${({ theme }) => theme.colors.dark}; font-size: 11px; font-weight: 900; letter-spacing: .1em; text-decoration: none; text-transform: uppercase; svg { color: #cf2d7d; font-size: 17px; }`;
export const Title = styled.h2`max-width: 760px; font-size: ${({ theme }) => theme.typography.sizes.section}; font-weight: 900; line-height: .96; letter-spacing: -.055em; em { color: #747a71; font-style: normal; }`;
export const Intro = styled.p`color: #5c6164; font-size: 16px; line-height: 1.7;`;
export const Grid = styled.div`display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: 22px; article { min-width: 0; } @media (max-width: ${({ theme }) => theme.breakpoints.sm}) { grid-template-columns: 1fr; }`;
export const PostLink = styled.a`position: relative; display: flex; flex-direction: column; overflow: hidden; border-radius: ${({ theme }) => theme.radii.lg}; color: ${({ theme }) => theme.colors.text}; background: ${({ theme }) => theme.colors.dark}; text-decoration: none; box-shadow: 0 24px 60px rgba(9,11,13,.13);`;
export const Media = styled.span`position: relative; aspect-ratio: 1 / 1; display: grid; place-items: center; overflow: hidden; isolation: isolate; background: #090b0d; &::after { content: ''; position: absolute; inset: 0; z-index: 2; border: 1px solid rgba(255,255,255,.1); pointer-events: none; }`;
export const MediaBackdrop = styled.img`position: absolute; inset: -7%; z-index: 0; width: 114%; height: 114%; object-fit: cover; filter: blur(28px) saturate(.8) brightness(.46); opacity: .62; transform: scale(1.03); transition: transform 800ms ${({ theme }) => theme.motion.ease}; ${PostLink}:hover & { transform: scale(1.08); }`;
export const PostImage = styled.img`position: relative; z-index: 1; width: 100%; height: 100%; display: block; object-fit: contain; filter: drop-shadow(0 18px 32px rgba(0,0,0,.28)); transition: transform 700ms ${({ theme }) => theme.motion.ease}; ${PostLink}:hover & { transform: scale(1.015); }`;
export const Overlay = styled.span`display: none;`;
export const PostNumber = styled.span`position: absolute; top: 18px; left: 18px; width: 40px; height: 40px; display: grid; place-items: center; border-radius: 50%; color: ${({ theme }) => theme.colors.dark}; background: ${({ theme }) => theme.colors.accent}; font-size: 10px; font-weight: 900;`;
export const Open = styled.span`position: absolute; top: 18px; right: 18px; width: 40px; height: 40px; display: grid; place-items: center; border: 1px solid rgba(255,255,255,.2); border-radius: 50%; background: rgba(9,11,13,.56); backdrop-filter: blur(10px);`;
export const PostCopy = styled.span`position: relative; min-height: 132px; padding: 24px 26px 28px; display: flex; flex-direction: column; align-items: flex-start; justify-content: center; gap: 8px; span { color: ${({ theme }) => theme.colors.accent}; font-size: 9px; font-weight: 900; letter-spacing: .1em; text-transform: uppercase; } strong { max-width: 500px; font-size: clamp(22px,2.5vw,34px); line-height: 1.08; letter-spacing: -.035em; }`;
export const ProfileLink = styled.a`width: fit-content; margin: 44px auto 0; padding: 14px 0; display: flex; align-items: center; gap: 10px; border-bottom: 1px solid rgba(9,11,13,.32); color: ${({ theme }) => theme.colors.dark}; font-size: 13px; font-weight: 900; text-decoration: none;`;
